apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-green
spec:
  {{ if .Values.green.enabled }}
  replicas: {{ .Values.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}  
  selector:
    matchLabels:
      app: {{ .Values.app }}
      color: green
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        color: green
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.green.tag }}"
          imagePullPolicy: Always
          name: {{ .Values.app }}-{{ .Values.image }}
          ports:
            - containerPort: 80
